- name: handler_copying
  copy:
    src: "{{ item }}"
    dest: /var/www/html/{{ item }}
  loop: "{{ my_files }}"
  notify: template_copying

- name: template_copying
  template:
    src: index.html.j2
    dest: /var/www/html/index.html
  notify: handler_restart
  
- name: handler_restart
  sysvinit:
    name: "{{ package_name }}"
    state: restarted
    enabled: yes


