- name: my play with handlers
  gather_facts: false
  hosts: 172.17.0.2

  tasks:
  - name: my task1 with handlers
    apt:
      name: nginx
    notify: my_handler

  handlers:
  - name: my_handler
    sysvinit:
      name: nginx
      state: restarted
      enabled: yes