- name: play1
  gather_facts: false
  hosts: 172.17.0.2
  vars:
    my_list:
      - nginx
      - curl
      - ssh
      - sudo
  tasks:
  - name: task1
    apt:
      name: "{{ item }}"
      state: latest
    loop: "{{ my_list }}"
