- name: play1
  gather_facts: false
  hosts: 172.17.0.2
  vars:
    package_name: nginx
    package_state: latest

  tasks:
  - name: task1
    apt:
      name: "{{ package_name }}"
      state: "{{ package_state }}"