FROM ubuntu
RUN apt-get update && apt-get install -y ssh && apt install sudo -y
RUN adduser ansible
RUN echo 'ansible:123' | chpasswd
RUN usermod -aG sudo ansible
ENTRYPOINT service ssh restart && bash